# Generated by Django 5.2.7 on 2025-12-17 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0004_alter_dependenciaactivo_options_and_more'),
        ('novedades', '0003_novedad_estado'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.PositiveIntegerField(editable=False, unique=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la OT')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción y alcance')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('por_iniciar', 'Por iniciar'), ('en_ejecucion', 'En ejecución'), ('en_espera', 'En espera'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_cierre_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre comprometida')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='activos.nodoactivo', verbose_name='Equipo o activo')),
                ('novedad_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='novedades.novedad', verbose_name='Novedad origen')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='personal.tecnicooperativo', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('por_iniciar', 'Por iniciar'), ('en_ejecucion', 'En ejecución'), ('en_espera', 'En espera'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Estado asociado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Comentario')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ot', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ot.workorder', verbose_name='Orden de trabajo')),
            ],
            options={
                'verbose_name': 'Evento de OT',
                'verbose_name_plural': 'Eventos de OT',
                'ordering': ['-creado_el'],
            },
        ),
    ]
