# Generated by Django 5.2.7 on 2026-01-08 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0006_actividadnovedad_remove_novedad_atencion_en_and_more'),
        ('ot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='novedades.actividadnovedad', verbose_name='Actividad'),
        ),
    ]
