# Generated by Django 5.2.7 on 2026-01-08 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0002_workorder_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderEventoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ot/eventos/%Y/%m/%d/', verbose_name='Foto')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ot_fotos', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ot.workorderevento', verbose_name='Evento de OT')),
            ],
            options={
                'verbose_name': 'Foto de evento de OT',
                'verbose_name_plural': 'Fotos de eventos de OT',
                'ordering': ['-creado_el'],
            },
        ),
    ]
