# Generated by Django 5.2.7 on 2026-01-08 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0003_workordereventofoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workordereventofoto',
            options={'ordering': ['-creado_el'], 'verbose_name': 'Archivo de evento de OT', 'verbose_name_plural': 'Archivos de eventos de OT'},
        ),
        migrations.AlterField(
            model_name='workordereventofoto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='ot.workorderevento', verbose_name='Evento de OT'),
        ),
        migrations.AlterField(
            model_name='workordereventofoto',
            name='imagen',
            field=models.FileField(upload_to='ot/eventos/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.CreateModel(
            name='WorkOrderAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ot/adjuntos/%Y/%m/%d/', verbose_name='Archivo')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_adjuntos', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='ot.workorder', verbose_name='Orden de trabajo')),
            ],
            options={
                'verbose_name': 'Archivo de OT',
                'verbose_name_plural': 'Archivos de OT',
                'ordering': ['-creado_el'],
            },
        ),
    ]
