# Generated by Django 5.2.7 on 2026-01-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0004_alter_workordereventofoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='estado',
            field=models.CharField(choices=[('reportada', 'Reportada'), ('por_iniciar', 'Por iniciar'), ('en_ejecucion', 'En ejecución'), ('en_espera', 'En espera'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='prioridad',
            field=models.CharField(choices=[('reportada', 'Reportada'), ('por_iniciar', 'Por iniciar'), ('en_ejecucion', 'En ejecución'), ('en_espera', 'En espera'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='reportada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='workorderevento',
            name='estado',
            field=models.CharField(choices=[('reportada', 'Reportada'), ('por_iniciar', 'Por iniciar'), ('en_ejecucion', 'En ejecución'), ('en_espera', 'En espera'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Estado asociado'),
        ),
    ]
