# Generated by Django 5.2.7 on 2026-01-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0005_alter_workorder_estado_alter_workorder_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
    ]
