# Generated by Django 5.2.7 on 2025-12-17 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0004_alter_dependenciaactivo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Campo padre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Campo padre',
                'verbose_name_plural': 'Campos padre',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CampoHijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Campo hijo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='novedades.campopadre', verbose_name='Campo padre')),
            ],
            options={
                'verbose_name': 'Campo hijo',
                'verbose_name_plural': 'Campos hijo',
                'ordering': ['padre__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la novedad')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='activos.nodoactivo', verbose_name='Equipo o molde')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubopcionCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de subopción')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código / referencia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('campo_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subopciones', to='novedades.campohijo', verbose_name='Campo hijo')),
            ],
            options={
                'verbose_name': 'Subopción',
                'verbose_name_plural': 'Subopciones',
                'ordering': ['campo_hijo__padre__nombre', 'campo_hijo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NovedadDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=255, verbose_name='Comentario o detalle')),
                ('campo_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='novedades.campohijo', verbose_name='Campo hijo')),
                ('campo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='novedades.campopadre', verbose_name='Campo padre')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='novedades.novedad', verbose_name='Novedad')),
                ('subopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='novedades.subopcioncampo', verbose_name='Subopción seleccionada')),
            ],
            options={
                'verbose_name': 'Detalle de novedad',
                'verbose_name_plural': 'Detalles de novedad',
                'ordering': ['novedad', 'campo_padre__nombre', 'campo_hijo__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='campohijo',
            constraint=models.UniqueConstraint(fields=('padre', 'nombre'), name='unique_campo_hijo_por_padre'),
        ),
        migrations.AddConstraint(
            model_name='subopcioncampo',
            constraint=models.UniqueConstraint(fields=('campo_hijo', 'nombre'), name='unique_subopcion_por_campo_hijo'),
        ),
    ]
