# Generated by Django 5.2.7 on 2025-12-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedaddetalle',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='novedades/evidencias/', verbose_name='Evidencia (imagen)'),
        ),
    ]
