# Generated by Django 5.2.7 on 2025-12-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_novedaddetalle_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
