# Generated by Django 5.2.7 on 2026-01-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_novedad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='atencion_en',
            field=models.CharField(choices=[('planta', 'Atención en planta'), ('taller', 'Atención en taller')], default='planta', max_length=20, verbose_name='Atención en'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
    ]
