# Generated by Django 5.2.7 on 2026-01-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0004_novedad_atencion_en_alter_novedad_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
