# Generated by Django 5.2.7 on 2026-01-07 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0005_alter_novedad_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Actividad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Actividad de novedad',
                'verbose_name_plural': 'Actividades de novedades',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='atencion_en',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='titulo',
        ),
        migrations.AddField(
            model_name='novedad',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='novedades.actividadnovedad', verbose_name='Actividad'),
        ),
    ]
