# Generated by Django 5.2.7 on 2026-01-11 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_catalogoparte_plantillanodoiso_and_more'),
        ('novedades', '0006_actividadnovedad_remove_novedad_atencion_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionPlantaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novedad_detalle_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('fecha_novedad', models.DateField(verbose_name='Fecha de la novedad')),
                ('campo_padre', models.CharField(max_length=150, verbose_name='Campo padre')),
                ('campo_hijo', models.CharField(max_length=150, verbose_name='Campo hijo')),
                ('subopcion', models.CharField(blank=True, max_length=150, verbose_name='Subopción')),
                ('comentario', models.CharField(blank=True, max_length=255, verbose_name='Comentario o detalle')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_atencion_planta', to='activos.nodoactivo', verbose_name='Equipo o molde')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_atencion_planta', to='novedades.novedad', verbose_name='Novedad')),
            ],
            options={
                'verbose_name': 'Detalle Atención Planta',
                'verbose_name_plural': 'Detalles Atención Planta',
                'ordering': ['-fecha_novedad', '-id'],
            },
        ),
    ]
