# Generated by Django 5.2.7 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0007_atencionplantadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionplantadetalle',
            name='estado_atencion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida')], default='PENDIENTE', max_length=10, verbose_name='Estado de atención'),
        ),
        migrations.AddField(
            model_name='atencionplantadetalle',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='atencionplantadetalle',
            name='tiempo_empleado_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo empleado (min)'),
        ),
    ]
