# Generated by Django 5.2.7 on 2026-01-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0008_atencionplantadetalle_estado_atencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionplantadetalle',
            name='estado_atencion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizada', 'Finalizada')], default='pendiente', max_length=10, verbose_name='Estado de atención'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
