# Generated by Django 5.2.7 on 2026-01-12 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0011_alter_novedad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de la novedad'),
        ),
    ]
