# Generated by Django 5.2.7 on 2026-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0012_alter_novedad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionplantadetalle',
            name='tipo_novedad',
            field=models.CharField(choices=[('atencion_planta', 'Atención planta'), ('alistamiento', 'Alistamiento')], default='atencion_planta', max_length=20, verbose_name='Tipo de novedad'),
        ),
    ]
