# Generated by Django 5.2.7 on 2026-01-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0013_atencionplantadetalle_tipo_novedad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={},
        ),
    ]
