# Generated by Django 5.2.7 on 2026-01-12 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_catalogoparte_plantillanodoiso_and_more'),
        ('novedades', '0014_alter_novedad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
        migrations.AddField(
            model_name='novedad',
            name='equipo_obligatorio_cumplimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_obligatorio_cumplimiento', to='activos.nodoactivo', verbose_name='Equipo obligatorio de cumplimiento'),
        ),
    ]
