# Generated by Django 5.2.7 on 2026-01-12 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_catalogoparte_plantillanodoiso_and_more'),
        ('novedades', '0015_alter_novedad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionplantadetalle',
            name='equipo_obligatorio_cumplimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_atencion_planta_obligatorio', to='activos.nodoactivo', verbose_name='Equipo obligatorio de cumplimiento'),
        ),
    ]
