# Generated by Django 5.2.7 on 2025-12-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas_documentos/')),
                ('tipo', models.CharField(choices=[('reporte', 'Reporte'), ('orden', 'Orden de trabajo')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
