# Generated by Django 5.2.7 on 2025-10-20 02:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0004_alter_dependenciaactivo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=50, unique=True, verbose_name='N.° identificación')),
                ('especialidad', models.CharField(max_length=150, verbose_name='Especialidad')),
                ('telefono_contacto', models.CharField(max_length=30, verbose_name='Teléfono de contacto')),
                ('correo_corporativo', models.EmailField(blank=True, max_length=254, verbose_name='Correo corporativo')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'En licencia')], default='activo', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tecnicos', to='activos.perfilusuario', verbose_name='Perfil organizacional')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_operativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Técnico operativo',
                'verbose_name_plural': 'Técnicos operativos',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del turno')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio del turno')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin del turno')),
                ('color', models.CharField(default='#2563eb', help_text='Color en formato HEX para calendarios', max_length=9, verbose_name='Color')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tecnicos', models.ManyToManyField(blank=True, related_name='turnos', to='personal.tecnicooperativo', verbose_name='Técnicos asignados')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('enfermedad', 'Enfermedad'), ('permiso', 'Permiso'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('motivo', models.TextField(verbose_name='Motivo o detalle')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='personal.tecnicooperativo', verbose_name='Técnico')),
                ('turno_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias', to='personal.turno', verbose_name='Turno relacionado')),
            ],
            options={
                'verbose_name': 'Ausencia',
                'verbose_name_plural': 'Ausencias',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='ausencia_fecha_fin_gte_inicio')],
            },
        ),
    ]
