# Generated by Django 5.2.7 on 2026-01-09 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnicooperativo',
            options={'ordering': ['user__last_name', 'user__first_name', 'nombre'], 'verbose_name': 'Técnico operativo', 'verbose_name_plural': 'Técnicos operativos'},
        ),
        migrations.AddField(
            model_name='tecnicooperativo',
            name='nombre',
            field=models.CharField(blank=True, help_text='Usa este campo si el técnico no tiene usuario.', max_length=150, verbose_name='Nombre del técnico'),
        ),
        migrations.AlterField(
            model_name='tecnicooperativo',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Asocia un usuario del sistema si el técnico inicia sesión.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_operativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
