# Generated by Django 5.2.7 on 2026-01-09 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_catalogoparte_plantillanodoiso_and_more'),
        ('personal', '0002_alter_tecnicooperativo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnicooperativo',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tecnicos', to='activos.organizacion', verbose_name='Perfil organizacional'),
        ),
    ]
