# Generated by Django 5.2.7 on 2025-10-13 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelJerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nivel', models.IntegerField(verbose_name='Número de nivel')),
                ('nombre_nivel', models.CharField(max_length=100, verbose_name='Nombre del nivel')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_nivel_equipo', models.BooleanField(default=False, verbose_name='Es nivel de equipo principal')),
                ('requiere_tag', models.BooleanField(default=False, verbose_name='Requiere generación de TAG')),
                ('prefijo_tag', models.CharField(blank=True, max_length=10, verbose_name='Prefijo TAG')),
                ('formato_tag', models.CharField(blank=True, help_text='Ejemplo: {PREFIJO}-{CODIGO}-{SECUENCIA}', max_length=100, verbose_name='Formato TAG')),
                ('corresponde_iso_14224', models.IntegerField(blank=True, help_text='Nivel 1-9 según ISO 14224', null=True, verbose_name='Nivel ISO 14224 correspondiente')),
            ],
            options={
                'verbose_name': 'Nivel de jerarquía',
                'verbose_name_plural': 'Niveles de jerarquía',
                'ordering': ['organizacion', 'numero_nivel'],
            },
        ),
        migrations.CreateModel(
            name='ClaseEquipoISO14224',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel_taxonomico', models.IntegerField(default=6, verbose_name='Nivel taxonómico ISO 14224')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.claseequipoiso14224', verbose_name='Clase padre')),
            ],
            options={
                'verbose_name': 'Clase de equipo ISO 14224',
                'verbose_name_plural': 'Clases de equipos ISO 14224',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=100, verbose_name='Nombre del campo')),
                ('tipo_campo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('seleccion', 'Lista desplegable'), ('booleano', 'Sí/No'), ('archivo', 'Archivo')], max_length=20, verbose_name='Tipo de campo')),
                ('es_requerido', models.BooleanField(default=False, verbose_name='Es requerido')),
                ('opciones', models.JSONField(blank=True, help_text='Para selección: ["Opción 1", "Opción 2"]', null=True, verbose_name='Opciones')),
                ('valor_predeterminado', models.CharField(blank=True, max_length=200, verbose_name='Valor predeterminado')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('nivel_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='activos.niveljerarquia', verbose_name='Nivel de jerarquía')),
            ],
            options={
                'verbose_name': 'Campo personalizado',
                'verbose_name_plural': 'Campos personalizados',
                'ordering': ['nivel_jerarquia', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='NodoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='TAG automático')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('clase_equipo_iso', models.CharField(blank=True, max_length=100, verbose_name='Clase de equipo ISO 14224')),
                ('fabricante', models.CharField(blank=True, max_length=200, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio'), ('retirado', 'Retirado')], default='activo', max_length=50, verbose_name='Estado')),
                ('criticidad', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, verbose_name='Criticidad')),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=300, verbose_name='Ubicación física detallada')),
                ('datos_personalizados', models.JSONField(blank=True, default=dict, verbose_name='Datos personalizados')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='activos/imagenes/', verbose_name='Imagen')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('nivel_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activos.niveljerarquia', verbose_name='Nivel de jerarquía')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='activos.nodoactivo', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['organizacion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('manual', 'Manual'), ('plano', 'Plano'), ('certificado', 'Certificado'), ('ficha_tecnica', 'Ficha técnica'), ('foto', 'Fotografía'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('archivo', models.FileField(upload_to='activos/documentos/', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('subido_el', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='activos.nodoactivo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Documento de activo',
                'verbose_name_plural': 'Documentos de activos',
                'ordering': ['-subido_el'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='nodoactivo',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='niveljerarquia',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_jerarquia', to='activos.organizacion', verbose_name='Organización'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.organizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='PlantillaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('datos_predeterminados', models.JSONField(default=dict, verbose_name='Datos predeterminados')),
                ('es_activa', models.BooleanField(default=True, verbose_name='Está activa')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('clase_equipo_iso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.claseequipoiso14224', verbose_name='Clase de equipo ISO')),
                ('nivel_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.niveljerarquia', verbose_name='Nivel de jerarquía')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Plantilla de activo',
                'verbose_name_plural': 'Plantillas de activos',
                'ordering': ['organizacion', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='nodoactivo',
            index=models.Index(fields=['organizacion', 'nivel_jerarquia'], name='activos_nod_organiz_dd0353_idx'),
        ),
        migrations.AddIndex(
            model_name='nodoactivo',
            index=models.Index(fields=['tag'], name='activos_nod_tag_f1e90b_idx'),
        ),
        migrations.AddIndex(
            model_name='nodoactivo',
            index=models.Index(fields=['estado'], name='activos_nod_estado_f6c2ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodoactivo',
            unique_together={('organizacion', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='niveljerarquia',
            unique_together={('organizacion', 'numero_nivel')},
        ),
    ]
