# Generated by Django 5.2.7 on 2025-10-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Familia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Familia de Activo',
                'verbose_name_plural': 'Familias de Activos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DependenciaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Dependencia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='activos.nodoactivo', verbose_name='Activo Padre')),
            ],
            options={
                'verbose_name': 'Dependencia de Activo',
                'verbose_name_plural': 'Dependencias de Activos',
            },
        ),
        migrations.AddField(
            model_name='nodoactivo',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.familiaactivo', verbose_name='Familia del Activo'),
        ),
    ]
