# Generated by Django 5.2.7 on 2025-10-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_familiaactivo_dependenciaactivo_nodoactivo_familia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependenciaactivo',
            options={'ordering': ['nombre'], 'verbose_name': 'Dependencia de Activo', 'verbose_name_plural': 'Dependencias de Activos'},
        ),
    ]
