# Generated by Django 5.2.7 on 2025-10-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_dependenciaactivo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependenciaactivo',
            options={'ordering': ['activo_padre', 'nombre'], 'verbose_name': 'Dependencia de Activo', 'verbose_name_plural': 'Dependencias de Activos'},
        ),
        migrations.AddField(
            model_name='familiaactivo',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familias_activos', to='activos.organizacion', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='familiaactivo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Familia'),
        ),
        migrations.AddIndex(
            model_name='familiaactivo',
            index=models.Index(fields=['organizacion', 'nombre'], name='activos_fam_organiz_6f0228_idx'),
        ),
        migrations.AddConstraint(
            model_name='dependenciaactivo',
            constraint=models.UniqueConstraint(fields=('activo_padre', 'nombre'), name='unique_dependencia_por_activo'),
        ),
        migrations.AddConstraint(
            model_name='familiaactivo',
            constraint=models.UniqueConstraint(fields=('organizacion', 'nombre'), name='unique_familia_por_organizacion'),
        ),
    ]
