# Generated by Django 5.2.7 on 2025-12-27 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_alter_dependenciaactivo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=100, verbose_name='Código/SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('datos_tecnicos', models.JSONField(blank=True, default=dict, verbose_name='Datos técnicos')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Disponible para selección')),
            ],
            options={
                'verbose_name': 'Parte de catálogo',
                'verbose_name_plural': 'Catálogo de partes',
                'ordering': ['organizacion', 'codigo_sku'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaNodoISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del nodo')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código del nodo')),
                ('nivel_iso', models.IntegerField(help_text='Nivel 1-9 según jerarquía ISO 14224', verbose_name='Nivel ISO 14224')),
                ('datos_predeterminados', models.JSONField(blank=True, default=dict, verbose_name='Datos predeterminados para instanciación')),
            ],
            options={
                'verbose_name': 'Nodo de plantilla ISO',
                'verbose_name_plural': 'Nodos de plantilla ISO',
                'ordering': ['organizacion', 'nivel_iso', 'codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='niveljerarquia',
            constraint=models.CheckConstraint(condition=models.Q(('numero_nivel__gte', 1), ('numero_nivel__lte', 9)), name='nivel_jerarquia_rango_iso'),
        ),
        migrations.AddField(
            model_name='catalogoparte',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_partes', to='activos.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='nodoactivo',
            name='catalogo_parte',
            field=models.ForeignKey(blank=True, help_text='Solo aplicable para el último nivel ISO 14224 (Parte/Pieza).', null=True, on_delete=django.db.models.deletion.PROTECT, to='activos.catalogoparte', verbose_name='Referencia de catálogo (nivel 9)'),
        ),
        migrations.AddIndex(
            model_name='nodoactivo',
            index=models.Index(fields=['organizacion', 'parent'], name='activos_nod_organiz_460d99_idx'),
        ),
        migrations.AddField(
            model_name='plantillanodoiso',
            name='catalogo_parte',
            field=models.ForeignKey(blank=True, help_text='Solo para nodos de nivel 9 (parte/pieza).', null=True, on_delete=django.db.models.deletion.PROTECT, to='activos.catalogoparte', verbose_name='Parte sugerida'),
        ),
        migrations.AddField(
            model_name='plantillanodoiso',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos_plantilla_iso', to='activos.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='plantillanodoiso',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='activos.plantillanodoiso', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='plantillanodoiso',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos_iso', to='activos.plantillaactivo', verbose_name='Plantilla asociada'),
        ),
        migrations.AddIndex(
            model_name='catalogoparte',
            index=models.Index(fields=['organizacion', 'codigo_sku'], name='activos_cat_organiz_d103ec_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogoparte',
            index=models.Index(fields=['organizacion', 'es_activo'], name='activos_cat_organiz_07a5c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogoparte',
            constraint=models.UniqueConstraint(fields=('organizacion', 'codigo_sku'), name='unique_sku_por_organizacion'),
        ),
        migrations.AddConstraint(
            model_name='plantillanodoiso',
            constraint=models.UniqueConstraint(fields=('plantilla', 'codigo'), name='unique_codigo_por_plantilla'),
        ),
        migrations.AddConstraint(
            model_name='plantillanodoiso',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_iso__gte', 1), ('nivel_iso__lte', 9)), name='nivel_iso_rango_valido'),
        ),
    ]
