"""
Django settings for cmms project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from urllib.parse import urlparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path: Path) -> None:
    """Load a simple .env file into os.environ if present."""
    if not path.exists():
        return

    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


# Load local .env if present (safe in Railway: file usually doesn't exist)
load_env_file(BASE_DIR / ".env")


# ----------------------------
# SECURITY / DEBUG
# ----------------------------
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-t%oj$!9&_od*l3xgn2m@b_r4xff15zp_*=vqgzpz^!q)ui47#8",
)

DEBUG = os.getenv("DEBUG", "True").lower() in ("1", "true", "yes", "on")


def build_allowed_hosts() -> list[str]:
    """
    Allowed hosts:
    - Local dev
    - Railway default domain (*.up.railway.app)
    - Any explicit ALLOWED_HOSTS env var
    - Railway public domain env vars (if present)
    """
    defaults = ["localhost", "127.0.0.1", "[::1]", ".up.railway.app"]

    env_hosts = [
        host.strip()
        for host in os.getenv("ALLOWED_HOSTS", "").split(",")
        if host.strip()
    ]

    railway_domain = (
        os.getenv("RAILWAY_PUBLIC_DOMAIN")
        or os.getenv("RAILWAY_STATIC_URL")
        or os.getenv("RAILWAY_URL")
    )

    hosts = defaults + ([railway_domain] if railway_domain else []) + env_hosts

    normalized: list[str] = []
    for host in hosts:
        if not host:
            continue
        cleaned = host.strip()
        if cleaned.startswith(("http://", "https://")):
            cleaned = urlparse(cleaned).netloc
        if cleaned and cleaned not in normalized:
            normalized.append(cleaned)

    return normalized


ALLOWED_HOSTS = build_allowed_hosts()


def normalize_origin(value: str) -> str | None:
    cleaned = value.strip()
    if not cleaned:
        return None

    if cleaned.startswith(("http://", "https://")):
        return cleaned

    if cleaned.startswith("."):
        cleaned = f"*.{cleaned.lstrip('.') }"

    return f"https://{cleaned}"


def build_csrf_trusted_origins() -> list[str]:
    # Defaults for Railway deployments (covers app-name.up.railway.app)
    defaults = ["https://*.up.railway.app"]

    # Optional explicit list from env (comma-separated)
    env_origins = [
        x.strip()
        for x in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
        if x.strip()
    ]

    # Railway public domain env vars
    railway_domain = (
        os.getenv("RAILWAY_PUBLIC_DOMAIN")
        or os.getenv("RAILWAY_STATIC_URL")
        or os.getenv("RAILWAY_URL")
    )

    normalized: list[str] = []
    for origin in defaults + env_origins + ([railway_domain] if railway_domain else []):
        normalized_origin = normalize_origin(origin)
        if normalized_origin and normalized_origin not in normalized:
            normalized.append(normalized_origin)

    return normalized


# CSRF trusted origins (important on Railway if you use POST forms)
# Put in env like: CSRF_TRUSTED_ORIGINS=https://*.up.railway.app,https://tu-dominio.com
CSRF_TRUSTED_ORIGINS = build_csrf_trusted_origins()
# ----------------------------
# APPLICATION DEFINITION
# ----------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "activos",
    
    "personal",
    
    "novedades",
    "ot",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # <-- correct order
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cmms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "accounts" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                 "accounts.context_processors.tecnico_flags",
            ],
        },
    },
]

WSGI_APPLICATION = "cmms.wsgi.application"


# ----------------------------
# DATABASE (CORREGIDO + dj_database_url)
# ----------------------------
IS_RAILWAY = bool(os.getenv("RAILWAY_ENVIRONMENT"))

# Prefer these env vars for URL-based config
# - In Railway: DATABASE_URL can be mysql://...@mysql.railway.internal:3306/railway
# - In local: set DATABASE_URL to mysql://...@centerbeam.proxy.rlwy.net:14616/railway
DATABASE_URL = (
    os.getenv("DATABASE_URL")
    or os.getenv("DB_URL")
    or os.getenv("MYSQL_PUBLIC_URL")
    or os.getenv("MYSQL_URL")
    or os.getenv("MYSQL_MYSQL_URL")
)

# Optional manual local fallback (if you don't want a DATABASE_URL locally)
DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.mysql")
DB_NAME = os.getenv("DB_NAME", "DB_activos")
DB_USER = os.getenv("DB_USER", "root")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")
DB_HOST = os.getenv("DB_HOST", "127.0.0.1")
DB_PORT = os.getenv("DB_PORT", "3306")


def build_database_config() -> dict:
    # A) If URL exists, use dj_database_url (works for mysql://, postgres://)
    if DATABASE_URL:
        cfg = dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,
        )
        # Ensure charset for MySQL
        if "mysql" in cfg.get("ENGINE", ""):
            cfg.setdefault("OPTIONS", {})
            cfg["OPTIONS"].setdefault("charset", "utf8mb4")
        return cfg

    # B) Railway MySQL variables (if no URL was provided)
    # Railway often provides MYSQLHOST/MYSQLUSER/etc.
    if IS_RAILWAY and os.getenv("MYSQLHOST"):
        return {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("MYSQLDATABASE", ""),
            "USER": os.getenv("MYSQLUSER", ""),
            "PASSWORD": os.getenv("MYSQLPASSWORD", ""),
            "HOST": os.getenv("MYSQLHOST", "mysql.railway.internal"),
            "PORT": os.getenv("MYSQLPORT", "3306"),
            "OPTIONS": {"charset": "utf8mb4"},
        }

    # C) Local fallback
    cfg = {
        "ENGINE": DB_ENGINE,
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    }
    if "mysql" in cfg.get("ENGINE", ""):
        cfg.setdefault("OPTIONS", {})
        cfg["OPTIONS"].setdefault("charset", "utf8mb4")
    return cfg


DATABASES = {"default": build_database_config()}


# ----------------------------
# PASSWORD VALIDATION
# ----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ----------------------------
# INTERNATIONALIZATION
# ----------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True


# ----------------------------
# STATIC FILES
# ----------------------------
STATIC_URL = os.getenv("STATIC_URL", "/static/")

# Keep your app static folder
STATICFILES_DIRS = [
    BASE_DIR / "accounts" / "static",
]

STATIC_ROOT = (
    Path(os.getenv("STATIC_ROOT")) if os.getenv("STATIC_ROOT") else BASE_DIR / "staticfiles"
)

# WhiteNoise storage (optional but recommended in production)
# If you have issues, you can comment this out.
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ----------------------------
# MEDIA FILES
# ----------------------------
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT")) if os.getenv("MEDIA_ROOT") else BASE_DIR / "media"
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)


# ----------------------------
# AUTH REDIRECTS
# ----------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
LOGIN_URL = "login"
